### ISSUE TITLE
cider.nrepl.middleware.info/javadoc-info should take *remote-javadocs* into account

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider-nrepl#308]
Currently we use a manual regexp method, but I think that's mostly the same as taking `clojure.java.javadoc/*remote-javadocs*` into account, and doing that might be more extensible by 3rd party tools.
Not sure though. Does anyone actually use that variable?

**Comment by sanjayl** [comment]
@Malabarba , I think this commit introduces an error because the underlying `clojure.java.javadoc` function has a bug: `clojure.java.javadoc/*remote-javadocs*` hasn't been updated for java > 1.7.  Attempting to get a Javadoc while using a 1.8 JRE will mistakenly return the URL for the 1.7 Javadocs. For example, while using OpenJDK 1.8.0_66:
```clojure
(require '[cider.nrepl.test-session :as session])
(defn msg [x] (session/session-fixture #(session/message x)))

(msg {:op "info"
      :class "java.util.concurrent.ConcurrentHashMap"
      :member "mappingCount"}) ;;n.b., this method introduced in Java 1.8

(:javadoc *1)

=> "http://java.sun.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html#mappingCount()"
```
As you can see, the returned URL is for the 1.7 Javadoc that does not contain documentation for this new method. The correct URL should be `http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#mappingCount--`

On a related note, the URL format for Javadocs is different in 1.8 vs priors. The parentheses in the old URLs are now replaced with dashes. E.g:

```
OLD:
http://docs.oracle.com/javase/7/docs/api/java/lang/StringBuilder.html#capacity()

NEW:
http://docs.oracle.com/javase/8/docs/api/java/lang/StringBuilder.html#capacity--
```

**Comment by bbatsov** [comment]
Guess someone should fix this in Clojure. Or at least file a bug there.

**Comment by sanjayl** [comment]
@bbatsov, there's a [bug report and patches](http://dev.clojure.org/jira/browse/CLJ-1398) from mid-2014 as well as more recently, although I'm not sure if this will also fix the issue with parenthesis -> dashes in the URLs.

**Comment by bbatsov** [comment]
Got it. I wonder if doesn't make sense to patch this on our end instead of waiting for an upstream fix. The function is pretty simple after all.

**Comment by Malabarba** [comment]
>  I wonder if doesn't make sense to patch this on our end instead of waiting for an upstream fix. 

I fixed our `javadoc-info` function on the second commit referenced above. Or do you mean we should patch the actual functions from `clojure.java.javadoc`?

**Comment by bbatsov** [comment]
> Or do you mean we should patch the actual functions from clojure.java.javadoc?

More or less. I actually thought we can simply replace the offending function as it's pretty simple.

**Comment by sanjayl** [comment]
We also need to fix the back half of the URL, the parens to dashes issue
still there
