### ISSUE TITLE
No matching method found: write for class clojure.lang.Var

### ISSUE THREAD

**Issue by glittershark** [clojure-emacs/cider-nrepl#322]
As best as I can tell this has something to do with https://github.com/clojure-emacs/cider-nrepl/commit/da993f1798e230cbed21c2f142bc184edcc94d97 - specifically, I'm running a web-server application, and any time I attempt to load a page when said application is running from inside a cider REPL (with `cider-jack-in`) I get the error message in the subject line (without a stacktrace, disappointingly) - any time I run it from within a regular old `lein repl` or within a cider repl on version 0.11.0 everything works smoothly

A smattering of info that may or may not be useful:

- My application writes logs using [timbre](https://github.com/ptaoussanis/timbre)
- Java 1.8.0
- Emacs 24.5.1
- OS X El Capitan host machine
- Web server is using http-kit

**Comment by mveytsman** [comment]
I was just about to report the same error

It seems that the issue comes up when printing from a separate thread. Here's an easy to reproduce test case:

```
(def ex (atom nil))
(.start  (Thread. (fn [] (try  (println "hi") (catch Throwable e (reset! ex e)))) ))
```

## Expected behavior
Print "hi"
## Actual behavior
`ex` gets the following error:
user> ex
#atom[#error {
 :cause "No matching method found: write for class clojure.lang.Var"
 :via
 [{:type java.lang.IllegalArgumentException
   :message "No matching method found: write for class clojure.lang.Var"
   :at [clojure.lang.Reflector invokeMatchingMethod "Reflector.java" 53]}]
 :trace
 [[clojure.lang.Reflector invokeMatchingMethod "Reflector.java" 53]
  [clojure.lang.Reflector invokeInstanceMethod "Reflector.java" 28]
  [cider.nrepl.middleware.out$forking_printer$fn__8946 invoke "out.clj" 60]
  [cider.nrepl.middleware.out.proxy$java.io.Writer$ff19274a write nil -1]
  [java.io.PrintWriter write "PrintWriter.java" 456]
  [java.io.PrintWriter write "PrintWriter.java" 473]
  [clojure.core$fn__6086 invokeStatic "core_print.clj" 199]
  [clojure.core$fn__6086 invoke "core_print.clj" 191]
  [clojure.lang.MultiFn invoke "MultiFn.java" 233]
  [clojure.core$pr_on invokeStatic "core.clj" 3572]
  [clojure.core$pr invokeStatic "core.clj" 3575]
  [clojure.core$pr invoke "core.clj" 3575]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 646]
  [clojure.core$prn invokeStatic "core.clj" 3612]
  [clojure.core$prn doInvoke "core.clj" 3612]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 646]
  [clojure.core$println invokeStatic "core.clj" 3631]
  [clojure.core$println doInvoke "core.clj" 3631]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [user$eval19636$fn__19637 invoke "c3141b6c2399e5b21cac8970280918d7a9ea6c9a-init.clj" 47]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]} 0x1b213ea]
user> 
## Steps to reproduce the problem

Run the following in a cider-connected repl

```clojure
(def ex (atom nil))
(.start  (Thread. (fn [] (try  (println "hi") (catch Throwable e (reset! ex e)))) ))
```

## Environment & Version information

### cider-nrepl version

Latest 0.12-snapshot (0.12.0-20160314.135909-5)

### Java version

Java 1.8.0_60

### Operating system

OSX

**Comment by glittershark** [comment]
Thanks @Malabarba!
