### ISSUE TITLE
Cancelling prompt while debugging quits debugger

### ISSUE THREAD

**Issue by grammati** [clojure-emacs/cider-nrepl#339]
While debugging, do a command that results in a prompt for input - eg: eval or inject. Then change your mind, and hit C-g at the minibuffer prompt, because you have realized that you don't actually want to eval or inject anything right now.

Expected behavior: debugging continues from where you were.

Actual: the debugger quits completely.

**Comment by Malabarba** [comment]
The reason this happens is that the expression prompt is actually a separate debug command.
So when the user aborts the prompt we sort of **have** to quit the debugger.

The correct way to fix this would be to make the prompt be a part of the command that originated it. So, instead of sending `:inject` to the backend and then receiving a prompt expression, Emacs would need to know that `:inject` requires an expression and would present the prompt itself (and then sending them both together).

The “send them both together” part is already supported by the backend. So we'd only need to make the front end a little smarter.

**Comment by grammati** [comment]
@Malabarba, I have been wondering about whether we could just remove the "input-type" from the messages, and code the front end to have specific knowledge of the available debug commands. After all, it is a bit weird to have the back-end specifying key-bindings for the front-end. What do you think?

**Comment by Malabarba** [comment]
Yes. After we merged that PR I realised it was really weird for the backend to send the keys.

I originally implemented the `input-type` parameter because I figured not all operations would always be available.
For instance, the `:quit` operation is not available outside an `eval` op (which is very common when developing servers).

Currently, that's the only use for this feature, but I'd rather not lose this functionality. (Eventually we could also take this even further, like not sending the `:in` keyword if we know we can't step-in here, or not sending the `:locals` keyword if there are currently no local values.)

But I definitely agree it's not the backend's job to specify the keybinds.

**Comment by vspinu** [comment]
> Eventually we could also take this even further, like not sending the :in keyword if we know we can't step-in here, or not sending the :locals keyword if there are currently no local values.)

Actually this is already the case in PR #405, locals and commands what depend on those are not available when the form wasn't compiled with locals. Sending truncated version of commands works but for some reasons emacs still accepts those commands  and everything then blows.

**Comment by vspinu** [comment]
AFAICT this one has been fixed.
