### ISSUE TITLE
Eliminate all references to orchard in the tests

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider-nrepl#489]
Basically ever since we started processing orchard with MrAnderson the Travis build as been broken as we can't refer to orchard from tests, because of how MrAnderson works (the test ns-es are not processed and can't find `orchard`). 

See this conversation as well

![image](https://user-images.githubusercontent.com/103882/35348342-754dd6f4-0140-11e8-99d2-8a90cafbfd1c.png)

That's a simple task, but I don't have time for it now. I'd appreciate some help. //cc @xiongtx @gonewest818 @ckoparkar

**Comment by xiongtx** [comment]
Per [Slack discussion](https://clojurians.slack.com/archives/C0617A8PQ/p1516838696000104?thread_ts=1516829559.000214&cid=C0617A8PQ):

![image](https://user-images.githubusercontent.com/1624090/35407803-e807c778-01c1-11e8-882e-0f2c235c6068.png)

I'd vote for stop testing w/ `mranderson` until we finish porting Orchard. Or make `mranderson` rewrite test code as well.

**Comment by gonewest818** [comment]
I agree, assuming the end goal is “to only refer to your lib’s API in your tests”. Stopping to make mranderson rewrite the tests is just a distraction from porting.  Btw, it’s trivial to disable (temporarily) mranderson in tests, and I have those changes ready to commit if that’s the direction you want to take.

**Comment by xiongtx** [comment]
@gonewest818 I've already opened a PR to that effect in #493.

**Comment by bbatsov** [comment]
Btw, I think that for the 5 "problematic" tests it would be needed something like 10-20 minutes per test to restructure things, so it's not a big deal, but I'm fine with @xiongtx idea. We just have to be careful not to introduce new coupling between orchard and cider-nrepl while we continue with the extraction/restructuring of the code.

**Comment by gonewest818** [comment]
Documenting as I investigate this.

Within "make test-clj" the problematic tests seem to be
- [ ] `test/clj/cider/nrepl/middleware/info_test.clj`
- [ ] `test/clj/cider/nrepl/middleware/track_state_test.clj`
- [ ] `test/clj/cider/nrepl/middleware/refresh_test.clj`
- [ ] `test/clj/cider/nrepl/middleware/util/instrument_test.clj`
- [ ] `test/spec/cider/nrepl/middleware/info_test.clj`

and similarly within "make test-cljs"
- [ ] `test/cljs/cider/nrepl/middleware/cljs_inspect_test.clj`

Where "problematic" means that these are the 6 test namespaces throwing exceptions due to orchard dependencies.  Presumably restructuring these tests may still reveal other problems with the "mranderson-ized" tests but we can cross that bridge when we come to it.
