### ISSUE TITLE
Implicit Lein middleware causes a warning on Lein 2.8.3

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider-nrepl#584]
The approach we're using for to auto-inject cider-nrepl is causing some problems on the latest Lein - see https://www.reddit.com/r/Clojure/comments/abngff/lein_283_causing_trouble_with_middleware/

Right now that's just a warning, but presumably it will be removed at some point, so I guess we'll have to figure out a better way to modify the project settings with our plugin. `refactor-nrepl` (and pretty much every other similar plugin) suffers from the same problem. 

I've pinged @technomancy for his input here https://github.com/technomancy/leiningen/issues/2387, but if anyone has ideas what to do that'd be great. 

I seem to recall that @benedekfazekas came up with this approach, so maybe he has some ideas.

**Comment by benedekfazekas** [comment]
after a quick look on the quoted issues etc. it seems to me that the problem is not with how we inject the extra stuff for cider from the CLI (the feature I actually remember implementing) but rather that our projects use the implicit middleware approach. For the CLI injecting feature with `lein` we use the `lein update-in` command which is basically just

```
Perform arbitrary transformations on your project map.

Acts a lot like calling `clojure.core/update-in` on your project map
and then invoking a task on it, but with a few differences. Instead of
a vector of keys for reaching into nested maps, just mash keywords
together like ":repl-options:port". A single ":" refers to the map
root. Provide the arguments to f (which must be a resolvable var)
followed by "--", and then the task name and arguments to the task:

    $ lein update-in :dependencies conj "[slamhound \"1.1.3\"]" -- repl

Arguments: ([key-path f & args])
```

We could in theory use the same machinery to explicitly inject the names of our middlewares too. That would make a horrible long CL but should work...

I guess the best at this point is to wait and see what @technomancy says.

**Comment by benedekfazekas** [comment]
btw sorry for the accidental pinning of this issue...

**Comment by technomancy** [comment]
I've removed the warning here since it's unlikely the change we had in mind at the time will actually happen. https://github.com/technomancy/leiningen/commit/9791484a9be46005c39cf3e51be44cad497b5586

**Comment by bbatsov** [comment]
Lein 2.9 is out and we can close this.
