### ISSUE TITLE
Accessing local java files within the same project

### ISSUE THREAD

**Issue by lassemaatta** [clojure-emacs/cider-nrepl#700]
## Expected behavior

Given:
- A leiningen project
- with `:java-source-paths` pointing to a directory with java sources, 
- and a clojure namespace importing these local java classes

Then user should be able to:
- navigate from the clojure namespace to the java sources (`cider-find-var` applied on the class), and
- see the documentation of a class (`cider-doc`)

## Actual behavior

Everything works ok for
- java classes in the JDK
- java classes in dependencies (when using e.g. [enrich-classpath](https://github.com/clojure-emacs/enrich-classpath))

For local classes under `:java-source-paths` the above features do not work.

A related [discussion](https://clojurians.slack.com/archives/C0617A8PQ/p1626879275346700) in clojurians slack.

## Steps to reproduce the problem

An old project of mine exhibits this behaviour: [clj-soap](https://github.com/lassemaatta/clj-soap). 

For example, the namespace `clj-soap.entity.measurement` imports the `cljsoap.api.soap.Measurement` class.

### cider-nrepl version

`CIDER 1.2.0snapshot (package: 20210706.1151), nREPL 0.8.3`

### Java version

```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7)
OpenJDK 64-Bit Server VM (build 11.0.12+7, mixed mode)
```

### Operating system

`Linux desktop 5.13.4-arch2-1`

**Comment by vemv** [comment]
Thanks for the detailed report! It looks good to me.

As far as `enrich-classpath` (or its previous `esolve-java-sources-and-javadocs` incarnation) is concerned, that program mainly downloads .jars for third-party deps. For :java-source-paths , there's no .jar whatsoever to download from Maven, so the plugin has little to do (under its current implementation).

In order to successfully address this issue one should have to carefully inspect what Lein, cider-nrepl, Orchard, etc are doing. Not sure of which part is at 'fault' here.

I'll give it a shot. Anyway, does this issue ring a bell, @bbatsov ? It sounds like a thing that should work OOTB.

**Comment by Cartmanishere** [comment]
@lassemaatta I have faced a similar issue before. The problem is not with `cider-nrepl`. If the java file exists on the classpath then `info` can find the location and docs for you.

But `lein` does not put `java-source-paths` directory on the classpath. So I used `source-paths` to get `lein` to include put local java file directory on classpath.
```
  :java-source-paths ["src/java"]
  :source-paths ["src/java"]
```

This seems to work for me.  Now I can navigate to my java code from clojure.

**Comment by vemv** [comment]
Good observation! Might be a good thing to request in https://github.com/technomancy/leiningen/. It's an improvement that shouldn't hurt (for other use cases one has to be careful about how one grows the classpath. But for a .java source file I think there's no chance for conflict... don't quote me on that though ^^)

**Comment by vemv** [comment]
As an additional note, the `source-paths` trick works, but also places the Java sources at the head of the classpath. IME it's much cleaner to place it at the tail of the classpath.

This is the order that Lein applies:

https://github.com/technomancy/leiningen/blob/a0807fb5a28764e90285221a7d22041f1ed52de0/leiningen-core/src/leiningen/core/classpath.clj#L594-L601

Therefore if you add the sources to `resource-paths` instead, they will still be in the classpath but in a later position.

This is still not ideal (since the sources will still take precedence over things) but one gains a little bit. Will create an issue or PR against Lein soon enough.

**Comment by vemv** [comment]
The forthcoming cider.el release will do this automatically for us 🙌
